### ISSUE TITLE
The library behaves badly on malformed formulas

### ISSUE THREAD

**Issue by thunder7553** [psalaets/excel-formula-ast#2]
If you pass a malformed formula to the library, it will be stuck in a loop. 

For example:

``` javascript
const tokens=tokenize('SUM(')
const rootNode = buildTree(tokens)
```

**Comment by psalaets** [comment]
The algorithm guide I used (https://www.engr.mun.ca/~theo/Misc/exp_parsing.htm) has support for error checking but I didn't implement it.

I think this should be possible but will take some time to do.
