### ISSUE TITLE
Alpha/beta/stable release

### ISSUE THREAD

**Issue by hhsadiq** [psalaets/excel-formula-ast#7]
Hey guys,

You are doing an awesome work to generate AST representation of excel formulas. It is a hardwork and I would like to thank you guys for it.

I just wanted to ask what is current status of the project? Is it still in active development phase, or it has reached to alpha/beta/stable phase? How much excel formulae it has supported until now? I guess https://github.com/psalaets/excel-formula-tokenizer is also closely related to this project and will be almost on the same stage.

Best regards

**Comment by psalaets** [comment]
It seems pretty stable as long as you're only using english excel. Take a look at the test suite to see what it supports. Everything passes right now except some of the German formulas.

There's no more dev happening unless people submit PRs or bugs that I think I can fix. I'm not currently using this in any of my projects so I'm relying on other people to report issues.

**Comment by hhsadiq** [comment]
Awesome, we are at an initial phase of a project and after finalizing the requirements process we might be using `excel-formula-ast` to generate ASTs for excel formulae. And during this, sure will submit feedback or any found bug.

Just as a start, does this take care of really large nested formulae e.g. this one

```
={TRANSPOSE(Input!$P$153:$P$177)*B.Cashflow!$F$10:$AD$10*Input!$M$105/1000000*IF(AND(F.Sensitivities!$D$7="ON",F.Sensitivities!$E$15="ON"),(1+F.Sensitivities!$D$15),1)}
```

**Comment by psalaets** [comment]
Before you start a project with this, please note that my motivation to work on this library is low. The project I wrote this for never happened. Be prepared to fix your own issues and add your own enhancements.

**Comment by hhsadiq** [comment]
Sure. No problem.
